language: python

git:
  depth: 99999

sudo: required

services:
  - docker

matrix:
  include:
    - python: 3.6

before_install:
  - git submodule update --init --recursive
  - cp openfoam/manager/config.example.json openfoam/manager/config.development.json
  - (cd openfoam/manager/keys && ./create_keys.sh)

install:
  - docker-compose build middleware

script: 
  - echo "success"
