version: '3'
services:

  middleware:
    build:
      context: middleware
      dockerfile: Dockerfile
    ports:
     - "5000:5000"
    volumes:
     - ./middleware:/app
    depends_on:
     - postgres
    networks:
     - db_nw
  postgres:
    image: "postgres:latest"
    volumes:
     - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sg
      - POSTGRES_PASSWORD=sg
      - POSTGRES_DB=sg
    networks:
     - db_nw

  auth:
    build:
      context: auth
      dockerfile: Dockerfile
    ports:
     - "5050:5050"
    volumes:
      - ./auth:/app
    depends_on:
      - postgres_auth
    networks:
      - db_nw

  postgres_auth:
    image: "postgres:latest"
    volumes:
     - database_auth:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sg
      - POSTGRES_PASSWORD=sg
      - POSTGRES_DB=sg
    networks:
     - db_nw

  manager:
    build:
      context: openfoam/manager
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
      - "10023:22"
    volumes:
      - ./openfoam/manager:/app
    environment:
      - FLASK_CONFIGURATION=development
      - STORAGE_ACCOUNT_NAME
      - STORAGE_ACCOUNT_KEY
    depends_on:
    - middleware
    - simulator
    networks:
    - db_nw


  simulator:
    container_name: simulator
    build:
      context: openfoam/simulator
      dockerfile: Dockerfile

    # here we use the keys from the manager
    env_file:
     - openfoam/manager/keys/simulator.env

    ports:
    - "10022:22"
    privileged: true
    volumes:
    - ./openfoam/simulator:/app
    networks:
    - db_nw

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    depends_on:
    - manager
    - middleware
    - simulator
    networks:
    - db_nw
    volumes:
    - './frontend/src:/app/src'
    - '/app/node_modules'

networks:
  db_nw:
    driver: bridge
volumes:
  database:
  database_auth:
