version: '3'
services:
  middleware:
    build:
      context: gateway-middleware
      dockerfile: Dockerfile
    ports:
     - "5000:5000"
    volumes:
     - ./gateway-middleware:/app
    depends_on:
     - postgres
    networks:
     - db_nw
  postgres:
    image: "postgres:latest"
    volumes:
     - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sg
      - POSTGRES_PASSWORD=sg
      - POSTGRES_DB=sg
    networks:
     - db_nw

  auth:
    build:
      context: gateway-auth
      dockerfile: Dockerfile
    ports:
     - "6000:6000"
    volumes:
     - ./gateway-auth:/app
    depends_on:
     - postgres_auth
    networks:
     - db_nw

  postgres_auth:
    image: "postgres:latest"
    volumes:
     - database_auth:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sg
      - POSTGRES_PASSWORD=sg
      - POSTGRES_DB=sg
    networks:
     - db_nw

  job-manager:
    build:
      context: gateway-openfoam/gateway-job-manager-openfoam
      dockerfile: Dockerfile
    ports:
    - "5001:5001"
    - "10023:22"
    volumes:
    - ./gateway-openfoam/gateway-job-manager-openfoam:/app
    environment:
    - FLASK_CONFIGURATION=default
    depends_on:
    - middleware
    - simulator
    networks:
    - db_nw
  simulator:
    container_name: simulator-openfoam
    build:
      context: gateway-openfoam/gateway-simulator-openfoam
      dockerfile: Dockerfile

    # here we use the keys from the job-manager
    env_file:
     - gateway-openfoam/gateway-job-manager-openfoam/keys/simulator.env

    ports:
    - "10022:22"
    privileged: true
    volumes:
    - ./gateway-openfoam/gateway-simulator-openfoam:/app
    networks:
    - db_nw

  frontend:
    build:
      context: gateway-frontend
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    depends_on:
    - job-manager
    - middleware
    - simulator
    networks:
    - db_nw
    volumes:
    - './gateway-frontend/src:/app/src'
    - '/app/node_modules'

networks:
  db_nw:
    driver: bridge
volumes:
  database:
  database_auth:
