version: '3'
services:
  integration:
    container_name: integration  # required for integration_tests.sh
    build: .
    # command: tail -F /dev/null  # use for interactive testing
    command: pytest -s tests  # required for integration_tests.sh
    depends_on:
      - simulator
      - manager
    networks:
      - share
    environment:
      - STORAGE_ACCOUNT_NAME
      - STORAGE_ACCOUNT_KEY
    volumes:
      - .:/app
      - ../manager:/app/manager


  # auth components
  auth:
    build:
      context: ../auth
      dockerfile: Dockerfile
    ports:
      - '5050:5050'
    volumes:
      - ../auth:/app
    depends_on:
      - auth_database
    networks:
      - share
  auth_database:
    image: 'postgres:latest'
    volumes:
      - auth_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sg
      - POSTGRES_PASSWORD=sg
      - POSTGRES_DB=sg
    networks:
      - share

  # middleware components
  middleware:
    build:
      context: ../middleware
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ../middleware:/app
    depends_on:
      - middleware_database
    networks:
      - share
    # command: gunicorn -w 3 -b :5000 app:app --reload
  middleware_database:
    image: 'postgres:latest'
    volumes:
      - middleware_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sg
      - POSTGRES_PASSWORD=sg
      - POSTGRES_DB=sg
    networks:
      - share
  
  # openfoam components
  manager:
    build:
      context: ../manager
      dockerfile: Dockerfile
    ports:
      - '5010:5010'
      - '10023:22'
    volumes:
      - ../manager:/app
    environment:
      - FLASK_CONFIGURATION=dev
      - STORAGE_ACCOUNT_NAME
      - STORAGE_ACCOUNT_KEY
    depends_on:
      - middleware
      - simulator
    networks:
      - share
    # command: gunicorn -w 3 -b :5010 app:app --reload
  simulator:
    build:
      context: ../simulator
      dockerfile: Dockerfile
    # here we use the keys from the manager
    env_file:
      - ../manager/keys/simulator.env
    ports:
      - '10022:22'
    privileged: true
    volumes:
      - ../simulator:/app
    networks:
      - share

  

networks:
  share:
    driver: bridge
volumes:
  auth_volume:
  middleware_volume:
